// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient.proto

package via.sdj3.proofofconcept_v3.GrpcService;

public interface PatientObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patient.PatientObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
