// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public final class AppointmentOuterClass {
  private AppointmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021appointment.proto\022\013appointment\"r\n\016Appo" +
      "intmentObj\022\n\n\002id\030\001 \001(\005\022\022\n\npatient_id\030\002 \001" +
      "(\005\022\021\n\tdoctor_id\030\003 \001(\005\022\014\n\004date\030\004 \001(\t\022\014\n\004t" +
      "ime\030\005 \001(\t\022\021\n\tdiagnosis\030\006 \001(\t\"\033\n\rAppointm" +
      "entId\022\n\n\002id\030\001 \001(\005\",\n\016AppointmentDto\022\014\n\004d" +
      "ate\030\001 \001(\t\022\014\n\004time\030\002 \001(\t\")\n\023AppointmentRe" +
      "sponse\022\022\n\nsuccessful\030\001 \001(\0102\212\003\n\013Appointme" +
      "nt\022L\n\013CreateAsync\022\033.appointment.Appointm" +
      "entObj\032 .appointment.AppointmentResponse" +
      "\022G\n\014GetByIdAsync\022\032.appointment.Appointme" +
      "ntId\032\033.appointment.AppointmentObj\022I\n\rGet" +
      "ByDtoAsync\022\033.appointment.AppointmentDto\032" +
      "\033.appointment.AppointmentObj\022L\n\013UpdateAs" +
      "ync\022\033.appointment.AppointmentObj\032 .appoi" +
      "ntment.AppointmentResponse\022K\n\013DeleteAsyn" +
      "c\022\032.appointment.AppointmentId\032 .appointm" +
      "ent.AppointmentResponseB6\n2via.sdj3.proo" +
      "fofconcept_v3.GrpcService.appointmentP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_appointment_AppointmentObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_appointment_AppointmentObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentObj_descriptor,
        new java.lang.String[] { "Id", "PatientId", "DoctorId", "Date", "Time", "Diagnosis", });
    internal_static_appointment_AppointmentId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_appointment_AppointmentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_appointment_AppointmentDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_appointment_AppointmentDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentDto_descriptor,
        new java.lang.String[] { "Date", "Time", });
    internal_static_appointment_AppointmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_appointment_AppointmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentResponse_descriptor,
        new java.lang.String[] { "Successful", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
