// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public final class AppointmentOuterClass {
  private AppointmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_RequestFindAppointmentsForDoctorObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_RequestFindAppointmentsForDoctorObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021appointment.proto\022\013appointment\"\202\001\n\016App" +
      "ointmentObj\022\n\n\002id\030\001 \001(\005\022\022\n\npatient_id\030\002 " +
      "\001(\005\022\021\n\tdoctor_id\030\003 \001(\005\022\014\n\004date\030\004 \001(\t\022\014\n\004" +
      "time\030\005 \001(\t\022\021\n\tdiagnosis\030\006 \001(\t\022\016\n\006status\030" +
      "\007 \001(\010\"\033\n\rAppointmentId\022\n\n\002id\030\001 \001(\005\",\n\016Ap" +
      "pointmentDto\022\014\n\004date\030\001 \001(\t\022\014\n\004time\030\002 \001(\t" +
      "\")\n\023AppointmentResponse\022\022\n\nsuccessful\030\001 " +
      "\001(\010\"D\n\017AppointmentList\0221\n\014appointments\030\001" +
      " \003(\0132\033.appointment.AppointmentObj\"?\n#Req" +
      "uestFindAppointmentsForDoctorObj\022\014\n\004date" +
      "\030\001 \001(\t\022\n\n\002id\030\002 \001(\0052\362\003\n\013Appointment\022G\n\013Cr" +
      "eateAsync\022\033.appointment.AppointmentObj\032\033" +
      ".appointment.AppointmentObj\022G\n\014GetByIdAs" +
      "ync\022\032.appointment.AppointmentId\032\033.appoin" +
      "tment.AppointmentObj\022I\n\rGetByDtoAsync\022\033." +
      "appointment.AppointmentDto\032\033.appointment" +
      ".AppointmentObj\022L\n\013UpdateAsync\022\033.appoint" +
      "ment.AppointmentObj\032 .appointment.Appoin" +
      "tmentResponse\022K\n\013DeleteAsync\022\032.appointme" +
      "nt.AppointmentId\032 .appointment.Appointme" +
      "ntResponse\022k\n\031findAppointmentsForDoctor\022" +
      "0.appointment.RequestFindAppointmentsFor" +
      "DoctorObj\032\034.appointment.AppointmentListB" +
      "6\n2via.sdj3.proofofconcept_v3.GrpcServic" +
      "e.appointmentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_appointment_AppointmentObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_appointment_AppointmentObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentObj_descriptor,
        new java.lang.String[] { "Id", "PatientId", "DoctorId", "Date", "Time", "Diagnosis", "Status", });
    internal_static_appointment_AppointmentId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_appointment_AppointmentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_appointment_AppointmentDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_appointment_AppointmentDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentDto_descriptor,
        new java.lang.String[] { "Date", "Time", });
    internal_static_appointment_AppointmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_appointment_AppointmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentResponse_descriptor,
        new java.lang.String[] { "Successful", });
    internal_static_appointment_AppointmentList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_appointment_AppointmentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentList_descriptor,
        new java.lang.String[] { "Appointments", });
    internal_static_appointment_RequestFindAppointmentsForDoctorObj_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_appointment_RequestFindAppointmentsForDoctorObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_RequestFindAppointmentsForDoctorObj_descriptor,
        new java.lang.String[] { "Date", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
