// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public final class DoctorOuterClass {
  private DoctorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorLogginObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorLogginObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorLogin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014doctor.proto\022\006doctor\"x\n\tDoctorObj\022\n\n\002i" +
      "d\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 " +
      "\001(\t\022\020\n\010fullname\030\004 \001(\t\022\026\n\016specialization\030" +
      "\005 \001(\t\022\021\n\tvalidated\030\006 \001(\010\"5\n\017DoctorLoggin" +
      "Obj\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"" +
      "\026\n\010DoctorId\022\n\n\002id\030\001 \001(\005\"$\n\016DoctorRespons" +
      "e\022\022\n\nsuccessful\030\001 \001(\010\"1\n\013DoctorLogin\022\020\n\010" +
      "username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t2\336\002\n\006Doc" +
      "tor\0223\n\013CreateAsync\022\021.doctor.DoctorObj\032\021." +
      "doctor.DoctorObj\022/\n\010GetAsync\022\020.doctor.Do" +
      "ctorId\032\021.doctor.DoctorObj\022B\n\016GetLogginAs" +
      "ync\022\027.doctor.DoctorLogginObj\032\027.doctor.Do" +
      "ctorLogginObj\0228\n\013UpdateAsync\022\021.doctor.Do" +
      "ctorObj\032\026.doctor.DoctorResponse\0227\n\013Delet" +
      "eAsync\022\020.doctor.DoctorId\032\026.doctor.Doctor" +
      "Response\0227\n\rLoginAsDoctor\022\023.doctor.Docto" +
      "rLogin\032\021.doctor.DoctorObjB1\n-via.sdj3.pr" +
      "oofofconcept_v3.GrpcService.doctorP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_doctor_DoctorObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doctor_DoctorObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorObj_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Fullname", "Specialization", "Validated", });
    internal_static_doctor_DoctorLogginObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_doctor_DoctorLogginObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorLogginObj_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_doctor_DoctorId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_doctor_DoctorId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_doctor_DoctorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_doctor_DoctorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorResponse_descriptor,
        new java.lang.String[] { "Successful", });
    internal_static_doctor_DoctorLogin_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_doctor_DoctorLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorLogin_descriptor,
        new java.lang.String[] { "Username", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
