// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public interface DoctorObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doctor.DoctorObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string specialization = 4;</code>
   * @return The specialization.
   */
  java.lang.String getSpecialization();
  /**
   * <code>string specialization = 4;</code>
   * @return The bytes for specialization.
   */
  com.google.protobuf.ByteString
      getSpecializationBytes();

  /**
   * <code>string password = 5;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 5;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
