// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public final class DoctorOuterClass {
  private DoctorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_Name_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014doctor.proto\022\006doctor\"a\n\tDoctorObj\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010username\030\003 \001(\t\022" +
      "\026\n\016specialization\030\004 \001(\t\022\020\n\010password\030\005 \001(" +
      "\t\"\024\n\004Name\022\014\n\004name\030\001 \001(\t2i\n\006Doctor\0223\n\013Cre" +
      "ateAsync\022\021.doctor.DoctorObj\032\021.doctor.Doc" +
      "torObj\022*\n\007GetUser\022\014.doctor.Name\032\021.doctor" +
      ".DoctorObjB*\n&via.sdj3.proofofconcept_v3" +
      ".GrpcServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_doctor_DoctorObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doctor_DoctorObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorObj_descriptor,
        new java.lang.String[] { "Id", "Name", "Username", "Specialization", "Password", });
    internal_static_doctor_Name_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_doctor_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_Name_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
