// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package appointment;

public final class AppointmentOuterClass {
  private AppointmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppointmentObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:appointment.AppointmentObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 patient_id = 2;</code>
     * @return The patientId.
     */
    int getPatientId();

    /**
     * <code>int32 doctor_id = 3;</code>
     * @return The doctorId.
     */
    int getDoctorId();

    /**
     * <code>string date = 4;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 4;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string time = 5;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>string time = 5;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>string diagnosis = 6;</code>
     * @return The diagnosis.
     */
    java.lang.String getDiagnosis();
    /**
     * <code>string diagnosis = 6;</code>
     * @return The bytes for diagnosis.
     */
    com.google.protobuf.ByteString
        getDiagnosisBytes();
  }
  /**
   * Protobuf type {@code appointment.AppointmentObj}
   */
  public  static final class AppointmentObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:appointment.AppointmentObj)
      AppointmentObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppointmentObj.newBuilder() to construct.
    private AppointmentObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppointmentObj() {
      date_ = "";
      time_ = "";
      diagnosis_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppointmentObj();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppointmentObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              patientId_ = input.readInt32();
              break;
            }
            case 24: {

              doctorId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              diagnosis_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              appointment.AppointmentOuterClass.AppointmentObj.class, appointment.AppointmentOuterClass.AppointmentObj.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 2;
    private int patientId_;
    /**
     * <code>int32 patient_id = 2;</code>
     * @return The patientId.
     */
    public int getPatientId() {
      return patientId_;
    }

    public static final int DOCTOR_ID_FIELD_NUMBER = 3;
    private int doctorId_;
    /**
     * <code>int32 doctor_id = 3;</code>
     * @return The doctorId.
     */
    public int getDoctorId() {
      return doctorId_;
    }

    public static final int DATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 4;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 4;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 5;</code>
     * @return The time.
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 5;</code>
     * @return The bytes for time.
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIAGNOSIS_FIELD_NUMBER = 6;
    private volatile java.lang.Object diagnosis_;
    /**
     * <code>string diagnosis = 6;</code>
     * @return The diagnosis.
     */
    public java.lang.String getDiagnosis() {
      java.lang.Object ref = diagnosis_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diagnosis_ = s;
        return s;
      }
    }
    /**
     * <code>string diagnosis = 6;</code>
     * @return The bytes for diagnosis.
     */
    public com.google.protobuf.ByteString
        getDiagnosisBytes() {
      java.lang.Object ref = diagnosis_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diagnosis_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (patientId_ != 0) {
        output.writeInt32(2, patientId_);
      }
      if (doctorId_ != 0) {
        output.writeInt32(3, doctorId_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, date_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, time_);
      }
      if (!getDiagnosisBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, diagnosis_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (patientId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, patientId_);
      }
      if (doctorId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, doctorId_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, date_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, time_);
      }
      if (!getDiagnosisBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, diagnosis_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof appointment.AppointmentOuterClass.AppointmentObj)) {
        return super.equals(obj);
      }
      appointment.AppointmentOuterClass.AppointmentObj other = (appointment.AppointmentOuterClass.AppointmentObj) obj;

      if (getId()
          != other.getId()) return false;
      if (getPatientId()
          != other.getPatientId()) return false;
      if (getDoctorId()
          != other.getDoctorId()) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getDiagnosis()
          .equals(other.getDiagnosis())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId();
      hash = (37 * hash) + DOCTOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDoctorId();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + DIAGNOSIS_FIELD_NUMBER;
      hash = (53 * hash) + getDiagnosis().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(appointment.AppointmentOuterClass.AppointmentObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code appointment.AppointmentObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:appointment.AppointmentObj)
        appointment.AppointmentOuterClass.AppointmentObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                appointment.AppointmentOuterClass.AppointmentObj.class, appointment.AppointmentOuterClass.AppointmentObj.Builder.class);
      }

      // Construct using appointment.AppointmentOuterClass.AppointmentObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        patientId_ = 0;

        doctorId_ = 0;

        date_ = "";

        time_ = "";

        diagnosis_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentObj_descriptor;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentObj getDefaultInstanceForType() {
        return appointment.AppointmentOuterClass.AppointmentObj.getDefaultInstance();
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentObj build() {
        appointment.AppointmentOuterClass.AppointmentObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentObj buildPartial() {
        appointment.AppointmentOuterClass.AppointmentObj result = new appointment.AppointmentOuterClass.AppointmentObj(this);
        result.id_ = id_;
        result.patientId_ = patientId_;
        result.doctorId_ = doctorId_;
        result.date_ = date_;
        result.time_ = time_;
        result.diagnosis_ = diagnosis_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof appointment.AppointmentOuterClass.AppointmentObj) {
          return mergeFrom((appointment.AppointmentOuterClass.AppointmentObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(appointment.AppointmentOuterClass.AppointmentObj other) {
        if (other == appointment.AppointmentOuterClass.AppointmentObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getPatientId() != 0) {
          setPatientId(other.getPatientId());
        }
        if (other.getDoctorId() != 0) {
          setDoctorId(other.getDoctorId());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (!other.getDiagnosis().isEmpty()) {
          diagnosis_ = other.diagnosis_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        appointment.AppointmentOuterClass.AppointmentObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (appointment.AppointmentOuterClass.AppointmentObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int patientId_ ;
      /**
       * <code>int32 patient_id = 2;</code>
       * @return The patientId.
       */
      public int getPatientId() {
        return patientId_;
      }
      /**
       * <code>int32 patient_id = 2;</code>
       * @param value The patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientId(int value) {
        
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 patient_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatientId() {
        
        patientId_ = 0;
        onChanged();
        return this;
      }

      private int doctorId_ ;
      /**
       * <code>int32 doctor_id = 3;</code>
       * @return The doctorId.
       */
      public int getDoctorId() {
        return doctorId_;
      }
      /**
       * <code>int32 doctor_id = 3;</code>
       * @param value The doctorId to set.
       * @return This builder for chaining.
       */
      public Builder setDoctorId(int value) {
        
        doctorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 doctor_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoctorId() {
        
        doctorId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 4;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 4;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 4;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 4;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 5;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 5;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 5;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 5;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object diagnosis_ = "";
      /**
       * <code>string diagnosis = 6;</code>
       * @return The diagnosis.
       */
      public java.lang.String getDiagnosis() {
        java.lang.Object ref = diagnosis_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          diagnosis_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string diagnosis = 6;</code>
       * @return The bytes for diagnosis.
       */
      public com.google.protobuf.ByteString
          getDiagnosisBytes() {
        java.lang.Object ref = diagnosis_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          diagnosis_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string diagnosis = 6;</code>
       * @param value The diagnosis to set.
       * @return This builder for chaining.
       */
      public Builder setDiagnosis(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diagnosis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string diagnosis = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiagnosis() {
        
        diagnosis_ = getDefaultInstance().getDiagnosis();
        onChanged();
        return this;
      }
      /**
       * <code>string diagnosis = 6;</code>
       * @param value The bytes for diagnosis to set.
       * @return This builder for chaining.
       */
      public Builder setDiagnosisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diagnosis_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:appointment.AppointmentObj)
    }

    // @@protoc_insertion_point(class_scope:appointment.AppointmentObj)
    private static final appointment.AppointmentOuterClass.AppointmentObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new appointment.AppointmentOuterClass.AppointmentObj();
    }

    public static appointment.AppointmentOuterClass.AppointmentObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppointmentObj>
        PARSER = new com.google.protobuf.AbstractParser<AppointmentObj>() {
      @java.lang.Override
      public AppointmentObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppointmentObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppointmentObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppointmentObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public appointment.AppointmentOuterClass.AppointmentObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppointmentIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:appointment.AppointmentId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code appointment.AppointmentId}
   */
  public  static final class AppointmentId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:appointment.AppointmentId)
      AppointmentIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppointmentId.newBuilder() to construct.
    private AppointmentId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppointmentId() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppointmentId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppointmentId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              appointment.AppointmentOuterClass.AppointmentId.class, appointment.AppointmentOuterClass.AppointmentId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof appointment.AppointmentOuterClass.AppointmentId)) {
        return super.equals(obj);
      }
      appointment.AppointmentOuterClass.AppointmentId other = (appointment.AppointmentOuterClass.AppointmentId) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(appointment.AppointmentOuterClass.AppointmentId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code appointment.AppointmentId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:appointment.AppointmentId)
        appointment.AppointmentOuterClass.AppointmentIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                appointment.AppointmentOuterClass.AppointmentId.class, appointment.AppointmentOuterClass.AppointmentId.Builder.class);
      }

      // Construct using appointment.AppointmentOuterClass.AppointmentId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentId_descriptor;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentId getDefaultInstanceForType() {
        return appointment.AppointmentOuterClass.AppointmentId.getDefaultInstance();
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentId build() {
        appointment.AppointmentOuterClass.AppointmentId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentId buildPartial() {
        appointment.AppointmentOuterClass.AppointmentId result = new appointment.AppointmentOuterClass.AppointmentId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof appointment.AppointmentOuterClass.AppointmentId) {
          return mergeFrom((appointment.AppointmentOuterClass.AppointmentId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(appointment.AppointmentOuterClass.AppointmentId other) {
        if (other == appointment.AppointmentOuterClass.AppointmentId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        appointment.AppointmentOuterClass.AppointmentId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (appointment.AppointmentOuterClass.AppointmentId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:appointment.AppointmentId)
    }

    // @@protoc_insertion_point(class_scope:appointment.AppointmentId)
    private static final appointment.AppointmentOuterClass.AppointmentId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new appointment.AppointmentOuterClass.AppointmentId();
    }

    public static appointment.AppointmentOuterClass.AppointmentId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppointmentId>
        PARSER = new com.google.protobuf.AbstractParser<AppointmentId>() {
      @java.lang.Override
      public AppointmentId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppointmentId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppointmentId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppointmentId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public appointment.AppointmentOuterClass.AppointmentId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppointmentDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:appointment.AppointmentDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string time = 2;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>string time = 2;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();
  }
  /**
   * Protobuf type {@code appointment.AppointmentDto}
   */
  public  static final class AppointmentDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:appointment.AppointmentDto)
      AppointmentDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppointmentDto.newBuilder() to construct.
    private AppointmentDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppointmentDto() {
      date_ = "";
      time_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppointmentDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppointmentDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              appointment.AppointmentOuterClass.AppointmentDto.class, appointment.AppointmentOuterClass.AppointmentDto.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 2;</code>
     * @return The time.
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 2;</code>
     * @return The bytes for time.
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof appointment.AppointmentOuterClass.AppointmentDto)) {
        return super.equals(obj);
      }
      appointment.AppointmentOuterClass.AppointmentDto other = (appointment.AppointmentOuterClass.AppointmentDto) obj;

      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(appointment.AppointmentOuterClass.AppointmentDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code appointment.AppointmentDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:appointment.AppointmentDto)
        appointment.AppointmentOuterClass.AppointmentDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentDto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                appointment.AppointmentOuterClass.AppointmentDto.class, appointment.AppointmentOuterClass.AppointmentDto.Builder.class);
      }

      // Construct using appointment.AppointmentOuterClass.AppointmentDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        date_ = "";

        time_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentDto_descriptor;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentDto getDefaultInstanceForType() {
        return appointment.AppointmentOuterClass.AppointmentDto.getDefaultInstance();
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentDto build() {
        appointment.AppointmentOuterClass.AppointmentDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentDto buildPartial() {
        appointment.AppointmentOuterClass.AppointmentDto result = new appointment.AppointmentOuterClass.AppointmentDto(this);
        result.date_ = date_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof appointment.AppointmentOuterClass.AppointmentDto) {
          return mergeFrom((appointment.AppointmentOuterClass.AppointmentDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(appointment.AppointmentOuterClass.AppointmentDto other) {
        if (other == appointment.AppointmentOuterClass.AppointmentDto.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        appointment.AppointmentOuterClass.AppointmentDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (appointment.AppointmentOuterClass.AppointmentDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 1;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 2;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 2;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 2;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:appointment.AppointmentDto)
    }

    // @@protoc_insertion_point(class_scope:appointment.AppointmentDto)
    private static final appointment.AppointmentOuterClass.AppointmentDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new appointment.AppointmentOuterClass.AppointmentDto();
    }

    public static appointment.AppointmentOuterClass.AppointmentDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppointmentDto>
        PARSER = new com.google.protobuf.AbstractParser<AppointmentDto>() {
      @java.lang.Override
      public AppointmentDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppointmentDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppointmentDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppointmentDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public appointment.AppointmentOuterClass.AppointmentDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppointmentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:appointment.AppointmentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool successful = 1;</code>
     * @return The successful.
     */
    boolean getSuccessful();
  }
  /**
   * Protobuf type {@code appointment.AppointmentResponse}
   */
  public  static final class AppointmentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:appointment.AppointmentResponse)
      AppointmentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppointmentResponse.newBuilder() to construct.
    private AppointmentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppointmentResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppointmentResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppointmentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              successful_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              appointment.AppointmentOuterClass.AppointmentResponse.class, appointment.AppointmentOuterClass.AppointmentResponse.Builder.class);
    }

    public static final int SUCCESSFUL_FIELD_NUMBER = 1;
    private boolean successful_;
    /**
     * <code>bool successful = 1;</code>
     * @return The successful.
     */
    public boolean getSuccessful() {
      return successful_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (successful_ != false) {
        output.writeBool(1, successful_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (successful_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, successful_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof appointment.AppointmentOuterClass.AppointmentResponse)) {
        return super.equals(obj);
      }
      appointment.AppointmentOuterClass.AppointmentResponse other = (appointment.AppointmentOuterClass.AppointmentResponse) obj;

      if (getSuccessful()
          != other.getSuccessful()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESSFUL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccessful());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static appointment.AppointmentOuterClass.AppointmentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(appointment.AppointmentOuterClass.AppointmentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code appointment.AppointmentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:appointment.AppointmentResponse)
        appointment.AppointmentOuterClass.AppointmentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                appointment.AppointmentOuterClass.AppointmentResponse.class, appointment.AppointmentOuterClass.AppointmentResponse.Builder.class);
      }

      // Construct using appointment.AppointmentOuterClass.AppointmentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        successful_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_descriptor;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentResponse getDefaultInstanceForType() {
        return appointment.AppointmentOuterClass.AppointmentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentResponse build() {
        appointment.AppointmentOuterClass.AppointmentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public appointment.AppointmentOuterClass.AppointmentResponse buildPartial() {
        appointment.AppointmentOuterClass.AppointmentResponse result = new appointment.AppointmentOuterClass.AppointmentResponse(this);
        result.successful_ = successful_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof appointment.AppointmentOuterClass.AppointmentResponse) {
          return mergeFrom((appointment.AppointmentOuterClass.AppointmentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(appointment.AppointmentOuterClass.AppointmentResponse other) {
        if (other == appointment.AppointmentOuterClass.AppointmentResponse.getDefaultInstance()) return this;
        if (other.getSuccessful() != false) {
          setSuccessful(other.getSuccessful());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        appointment.AppointmentOuterClass.AppointmentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (appointment.AppointmentOuterClass.AppointmentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean successful_ ;
      /**
       * <code>bool successful = 1;</code>
       * @return The successful.
       */
      public boolean getSuccessful() {
        return successful_;
      }
      /**
       * <code>bool successful = 1;</code>
       * @param value The successful to set.
       * @return This builder for chaining.
       */
      public Builder setSuccessful(boolean value) {
        
        successful_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool successful = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccessful() {
        
        successful_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:appointment.AppointmentResponse)
    }

    // @@protoc_insertion_point(class_scope:appointment.AppointmentResponse)
    private static final appointment.AppointmentOuterClass.AppointmentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new appointment.AppointmentOuterClass.AppointmentResponse();
    }

    public static appointment.AppointmentOuterClass.AppointmentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppointmentResponse>
        PARSER = new com.google.protobuf.AbstractParser<AppointmentResponse>() {
      @java.lang.Override
      public AppointmentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppointmentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppointmentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppointmentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public appointment.AppointmentOuterClass.AppointmentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentDto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021appointment.proto\022\013appointment\"r\n\016Appo" +
      "intmentObj\022\n\n\002id\030\001 \001(\005\022\022\n\npatient_id\030\002 \001" +
      "(\005\022\021\n\tdoctor_id\030\003 \001(\005\022\014\n\004date\030\004 \001(\t\022\014\n\004t" +
      "ime\030\005 \001(\t\022\021\n\tdiagnosis\030\006 \001(\t\"\033\n\rAppointm" +
      "entId\022\n\n\002id\030\001 \001(\005\",\n\016AppointmentDto\022\014\n\004d" +
      "ate\030\001 \001(\t\022\014\n\004time\030\002 \001(\t\")\n\023AppointmentRe" +
      "sponse\022\022\n\nsuccessful\030\001 \001(\0102\212\003\n\013Appointme" +
      "nt\022L\n\013CreateAsync\022\033.appointment.Appointm" +
      "entObj\032 .appointment.AppointmentResponse" +
      "\022G\n\014GetByIdAsync\022\032.appointment.Appointme" +
      "ntId\032\033.appointment.AppointmentObj\022I\n\rGet" +
      "ByDtoAsync\022\033.appointment.AppointmentDto\032" +
      "\033.appointment.AppointmentObj\022L\n\013UpdateAs" +
      "ync\022\033.appointment.AppointmentObj\032 .appoi" +
      "ntment.AppointmentResponse\022K\n\013DeleteAsyn" +
      "c\022\032.appointment.AppointmentId\032 .appointm" +
      "ent.AppointmentResponseB\016\252\002\013GrpcServiceb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_appointment_AppointmentObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_appointment_AppointmentObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentObj_descriptor,
        new java.lang.String[] { "Id", "PatientId", "DoctorId", "Date", "Time", "Diagnosis", });
    internal_static_appointment_AppointmentId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_appointment_AppointmentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_appointment_AppointmentDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_appointment_AppointmentDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentDto_descriptor,
        new java.lang.String[] { "Date", "Time", });
    internal_static_appointment_AppointmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_appointment_AppointmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentResponse_descriptor,
        new java.lang.String[] { "Successful", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
